### ISSUE TITLE
2.2.4 Resolve Receipt encourages authentication

### ISSUE THREAD

**Issue by robinbryce** [ietf-wg-scitt/draft-ietf-scitt-scrapi#14]
https://www.ietf.org/archive/id/draft-ietf-scitt-scrapi-01.html#name-resolve-receipt

I don't understand *why* this is desired:

"Authentication SHOULD be implemented for this endpoint"

If the material in a receipt is, or can be, considered private to the issuer, then this should be a MUST.

Instinctively I have always thought of receipts as essentially public documents. Whilst they are revealing, they are designed to be passed on to other parties.

If the intent is to permit implementations to provide for both public and private receipts, I think that model needs to be spelled out explicitly.

It would seem reasonable to me for Resolve Receipt to provide "the defined public aspects of a receipt" when the request was not authenticated. And the possibly sensitive parts otherwise

In practice, there are definitely usecases for obtaining a receipt for a statement issued by a different party. Its not clear at all to me how or if the authentication requirement here interacts with that.

**Comment by robinbryce** [comment]
I'm led to understand this SHOULD is intended to "solve" the issues of rate limiting and fairness. I think SCITT should have an opinion on whether anonoymous access to receipts for any statement is required of implementations. But whether or not it does consider it required, it seems very transparency service specific how the implications of this are dealt with. An Authentication requirement like this on these is confusing to me either way.

**Comment by roywill** [comment]
This is a tricky section.  We recommend that rate limiting could be used, but not MUST or SHOULD.  Within a corporation's network this may be a non-issue.  It is a solution to solve a potential problem, but it is up to the operator.

**Comment by JAG-UK** [comment]
This is related to things I'm working on already: I'll put up a PR later

**Comment by JAG-UK** [comment]
In PR #27 I have added an option for Transparency Services to return a 429 response, and have deliberately not included specific request detail in there so that the TS can choose any trigger (global or local) for this.

Let's see if that's enough: I don't think rate limiting is a good reason to enforce authentication

**Comment by achamayou** [comment]
The stance on authentication is inconsistent in the current document:

- [Register Signed Statement](https://github.com/ietf-wg-scitt/draft-ietf-scitt-scrapi/blob/main/draft-ietf-scitt-scrapi.md#register-signed-statement): "Authentication MAY be implemented"
- [Resolve Signed Statement](https://github.com/ietf-wg-scitt/draft-ietf-scitt-scrapi/blob/main/draft-ietf-scitt-scrapi.md#resolve-signed-statement): "Authentication SHOULD be implemented"

Surely we don't mean to place a higher authentication requirement on fetching transparent statements than on creating them? (same for Resolve Receipt)

Likewise, I think the fact that Authentication "SHOULD NOT" be implemented for [Resolve Issuer](https://github.com/ietf-wg-scitt/draft-ietf-scitt-scrapi/blob/main/draft-ietf-scitt-scrapi.md#resolve-issuer), nor for [Transparency Configuration](https://github.com/ietf-wg-scitt/draft-ietf-scitt-scrapi/blob/main/draft-ietf-scitt-scrapi.md#transparency-configuration) is a mistake, as @JAG-UK rightly pointed out in #46.

It seems to me that the only endpoint that MUST have authentication is Issue Statement (which in my opinion also does not belong in SCRAPI, it's a weird way to add signing to a transparency service, and I do not understand why it was shoehorned in).
Every other endpoint MAY implement authentication, because:

1. Not all transparency use cases are public. Transparency inside an organisation is a valid use case, and may legitimately require authentication, even on configuration and issuer endpoints.
2. It's a very practical way to implementing rate limiting or QoS for all use cases, public or otherwise.

Does that make sense to everyone? Did I miss something?

**Comment by SteveLasker** [comment]
Resolved by #52
