### ISSUE TITLE
Do we really need 2.2.7 Request Nonce?

### ISSUE THREAD

**Issue by JAG-UK** [ietf-wg-scitt/draft-ietf-scitt-scrapi#47]
It's not clear why this would be needed, and it doesn't reflect any patterns in the Architecture. Remove?

**Comment by achamayou** [comment]
@JAG-UK there's a reference to "proof of possession", so my guess it that this is meant to enable a flow where the client requests a nonce, includes it in the signed statement (protected header or payload) before signing and submission, to "prove" that they held the key at the time of submission, if it is substantially different from the time of signing.

I agree that this should be removed because:

1. It's poorly specified for its stated purpose, without mandatory transport-level security, it's possible to effectively DoS a client by using the nonce they requested quicker than they can. Without authentication, a malicious client can also spam the service for fresh nonce values, causing legitimate ones to fall out of the expiry window before they can be used.
3. There is no mention of a scenario where this is helpful or necessary.
4. If such a scenario emerges, where an issuer signs or has signed indiscriminately in advance, and it is desirable to be stricter about what can be made transparent, there are two easier mechanisms the registration policy can use that don't require an awkward stateful API extension such as this:
  - `iat` in the signed statement
  - a counter-signature with a submission control key (which may or may not be the same as one of the issuer keys)
Neither requires additional API surface, nor creates additional DoS opportunities.

Opened #49
